-- 年度別 期首/期末在庫スナップショット（方法C）
-- 年度更新時に資産ごとの「その年度の期首在庫・期末在庫」を凍結保存し、
-- 過去年度の差引残・在庫表を正確に再現できるようにする。

create table if not exists invent_fiscal_snapshots (
  id bigint generated by default as identity primary key,
  child_asset_id bigint not null references invent_child_assets(id),
  fiscal_year integer not null,            -- 会計年度の開始年（例: 2026 = 2026/7〜2027/6）
  opening_stock numeric not null default 0,-- その年度の期首在庫
  closing_stock numeric not null default 0,-- その年度の期末在庫（＝翌年度の期首）
  closed_at date not null,                 -- 年度更新の期末日
  created_at timestamptz not null default now(),
  unique (child_asset_id, fiscal_year)     -- 同一資産・同一年度は1件（年度更新の再実行で上書き）
);

create index if not exists idx_fiscal_snapshots_year on invent_fiscal_snapshots(fiscal_year);

-- RLS
alter table invent_fiscal_snapshots enable row level security;

drop policy if exists "invent_fiscal_snapshots_authenticated_select" on invent_fiscal_snapshots;
create policy "invent_fiscal_snapshots_authenticated_select"
on invent_fiscal_snapshots
for select
to authenticated
using (true);

drop policy if exists "invent_fiscal_snapshots_authenticated_insert" on invent_fiscal_snapshots;
create policy "invent_fiscal_snapshots_authenticated_insert"
on invent_fiscal_snapshots
for insert
to authenticated
with check (true);

drop policy if exists "invent_fiscal_snapshots_authenticated_update" on invent_fiscal_snapshots;
create policy "invent_fiscal_snapshots_authenticated_update"
on invent_fiscal_snapshots
for update
to authenticated
using (true)
with check (true);

drop policy if exists "invent_fiscal_snapshots_authenticated_delete" on invent_fiscal_snapshots;
create policy "invent_fiscal_snapshots_authenticated_delete"
on invent_fiscal_snapshots
for delete
to authenticated
using (true);
