-- 発注依頼テーブルとRLS設定
create table if not exists public.invent_order_requests (
  id bigint generated by default as identity primary key,
  child_asset_id bigint not null references public.invent_child_assets(id) on delete restrict,
  supplier_id bigint references public.invent_suppliers(id) on delete set null,
  asset_name text not null,
  supplier_name text not null default '発注先未設定',
  quantity integer not null check (quantity > 0),
  purchase_unit text,
  memo text,
  requested_by text not null,
  requested_at timestamptz not null default now(),
  status text not null default 'requested' check (status in ('requested', 'completed', 'cancelled')),
  completed_by text,
  completed_at timestamptz,
  email_sent_at timestamptz
);

create index if not exists invent_order_requests_status_requested_at_idx
  on public.invent_order_requests (status, requested_at desc);
create index if not exists invent_order_requests_supplier_id_idx
  on public.invent_order_requests (supplier_id);

alter table public.invent_order_requests enable row level security;

drop policy if exists "invent_order_requests_authenticated_select" on public.invent_order_requests;
create policy "invent_order_requests_authenticated_select"
  on public.invent_order_requests for select
  to authenticated
  using (true);

drop policy if exists "invent_order_requests_authenticated_insert" on public.invent_order_requests;
create policy "invent_order_requests_authenticated_insert"
  on public.invent_order_requests for insert
  to authenticated
  with check (auth.uid() is not null);

drop policy if exists "invent_order_requests_authenticated_update" on public.invent_order_requests;
create policy "invent_order_requests_authenticated_update"
  on public.invent_order_requests for update
  to authenticated
  using (true)
  with check (auth.uid() is not null);

-- 旧版SQLでRealtime対象に追加済みの場合は解除する。
do $$
begin
  if exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'invent_order_requests'
  ) then
    alter publication supabase_realtime drop table public.invent_order_requests;
  end if;
end
$$;
