-- 新規取引先の登録が
--   null value in column "id" of relation "invent_suppliers" violates not-null constraint
-- で失敗する問題の修正。
-- Supabase SQL Editor でこのファイル全体を1回実行する。

do $$
declare
  v_max bigint;
  v_sequence text;
  v_has_default boolean;
begin
  select (a.attidentity in ('a', 'd'))
         or exists (
           select 1 from pg_attrdef d
            where d.adrelid = a.attrelid and d.adnum = a.attnum
         )
    into v_has_default
    from pg_attribute a
    join pg_class c on c.oid = a.attrelid
    join pg_namespace n on n.oid = c.relnamespace
   where n.nspname = 'public'
     and c.relname = 'invent_suppliers'
     and a.attname = 'id'
     and a.attnum > 0
     and not a.attisdropped;

  if v_has_default is null then
    raise exception 'invent_suppliers.id 列が見つかりません。';
  end if;

  if not v_has_default then
    alter table public.invent_suppliers
      alter column id add generated by default as identity;
  end if;

  select coalesce(max(id), 0) into v_max from public.invent_suppliers;
  v_sequence := pg_get_serial_sequence('public.invent_suppliers', 'id');

  if v_max > 0 then
    perform setval(v_sequence, v_max, true);
  else
    perform setval(v_sequence, 1, false);
  end if;
end $$;

-- 確認用: identity が d または a なら設定済み。
select a.attidentity as identity,
       pg_get_serial_sequence('public.invent_suppliers', 'id') as sequence_name
  from pg_attribute a
  join pg_class c on c.oid = a.attrelid
  join pg_namespace n on n.oid = c.relnamespace
 where n.nspname = 'public'
   and c.relname = 'invent_suppliers'
   and a.attname = 'id';
