-- 新規資産の登録が
--   null value in column "id" of relation "invent_child_assets" violates not-null constraint
-- で失敗する問題の修正。
--
-- 原因: Excel からの移行時に id を明示指定して取り込んだため、id 列に採番の既定値
--       （identity / serial の nextval デフォルト）が設定されていない。
--       アプリは id を送らずに INSERT するため NULL となり NOT NULL 制約に違反する。
--
-- 対応: id 列に identity を付与し、既存データの最大 id の次から採番されるようにする。
--       既に採番設定がある表は何もしない（何度実行しても安全）。
--
-- 対象はアプリが行を新規追加する整数IDの表のみ。
--   - invent_child_assets : 資産マスタの新規登録
--   - invent_categories   : 「＋ 新しい分類を追加」
-- invent_parent_assets は 'P-0001' 形式のテキストIDを RPC 側で採番するため対象外。
-- invent_staff は変更しない運用のため対象外。

do $$
declare
  v_table   text;
  v_seq     text;
  v_max     bigint;
  v_has_def boolean;
begin
  foreach v_table in array array['invent_child_assets', 'invent_categories'] loop
    -- 表が無い環境ではスキップ
    if to_regclass('public.' || v_table) is null then
      raise notice '% : 表が存在しないためスキップします。', v_table;
      continue;
    end if;

    -- identity 指定（attidentity in ('a','d')）または default 定義があれば設定済み
    select (a.attidentity in ('a', 'd'))
           or exists (select 1 from pg_attrdef d where d.adrelid = a.attrelid and d.adnum = a.attnum)
      into v_has_def
      from pg_attribute a
      join pg_class c on c.oid = a.attrelid
      join pg_namespace n on n.oid = c.relnamespace
     where n.nspname = 'public'
       and c.relname = v_table
       and a.attname = 'id'
       and a.attnum > 0
       and not a.attisdropped;

    if v_has_def is null then
      raise notice '% : id 列が見つからないためスキップします。', v_table;
      continue;
    end if;

    if v_has_def then
      raise notice '% : id は既に採番設定済みのため変更しません。', v_table;
      continue;
    end if;

    execute format('alter table public.%I alter column id add generated by default as identity', v_table);

    -- 既存の最大 id の次から採番されるようにシーケンスを合わせる
    execute format('select coalesce(max(id), 0) from public.%I', v_table) into v_max;
    v_seq := pg_get_serial_sequence('public.' || v_table, 'id');

    if v_max > 0 then
      perform setval(v_seq, v_max, true);   -- 次は v_max + 1
    else
      perform setval(v_seq, 1, false);      -- 空の表は 1 から
    end if;

    raise notice '% : id に identity を設定しました。次のIDは % です。', v_table, greatest(v_max + 1, 1);
  end loop;
end $$;

-- 確認用: 設定後の既定値を表示する（a = always, d = by default, '' = 未設定）
select c.relname                             as table_name,
       a.attname                             as column_name,
       a.attidentity                         as identity,
       pg_get_expr(d.adbin, d.adrelid)       as column_default,
       pg_get_serial_sequence('public.' || c.relname, a.attname) as sequence_name
  from pg_attribute a
  join pg_class c     on c.oid = a.attrelid
  join pg_namespace n on n.oid = c.relnamespace
  left join pg_attrdef d on d.adrelid = a.attrelid and d.adnum = a.attnum
 where n.nspname = 'public'
   and c.relname in ('invent_child_assets', 'invent_categories')
   and a.attname = 'id';
